version: '3.4'

services:
  hotelreservationwebsite:
    container_name: hotelreservationwebsite
    image: ${DOCKER_REGISTRY-}hotelreservationwebsite
    build:
      context: .
      dockerfile: src\HotelReservationWebsite/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      -  hotelreservationwebsite:/app/data
  
  hotelreservationdatabase:
    container_name: hotelreservationdatabase 
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - hotelreservationdatabase:/var/opt/mssql

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  hotelreservationwebsite:
  hotelreservationdatabase:
