services:
  hotelreservationwebsite:
    container_name: hotelreservationwebsite
    image: dominikkielkowski/hotel-reservation-api:latest
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - hotelreservationwebsite:/app/data
    networks:
      - shared-network
  
  hotelreservationdatabase:
    container_name: hotelreservationdatabase
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - hotelreservationdatabase:/var/opt/mssql
    networks:
      - shared-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - shared-network
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - shared-network
  
  angular-web-client:
    container_name: angular-web-client
    image: dominikkielkowski/hotel-reservation-web-client:development
    ports:
      - "4200:80"

volumes:
  hotelreservationwebsite:
  hotelreservationdatabase:
  rabbitmq:

networks:
  shared-network: