version: '3.4'

services:
  hotelreservationwebsite:
    container_name: hotelreservationwebsite
    image: ${DOCKER_REGISTRY-}hotelreservationwebsite
    build:
      context: .
      dockerfile: src\HotelReservationWebsite/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      -  hotelreservationwebsite:/app/data
  
  hotelreservationdatabase:
    container_name: hotelreservationdatabase 
    image: postgres:latest
    environment: 
      - POSTGRES_DB=HotelReservationWebsite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432 
    volumes:
      - hotelreservationdatabase:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  hotelreservationwebsite:
  hotelreservationdatabase: